name: Steganophy LSB Audio Tool

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Testing encrypt
      run: |
        enc=`python testcase/test_encrypt.py`
        
    - name: Testing decrypt
      run: dec=`python testcase/test_decrypt.py`
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "encrypt testing: $enc. decrypt testing $dec"
        SLACK_TITLE: notify
        SLACK_USERNAME: slackbot
        SLACK_MSG_AUTHOR: bot